- Client/src/components/games/SnakeGame.jsx
- Client/src/components/games/SpaceType.jsx
Stores the high score in local storage. Implemented storage for Hungry Snake, Space typing, and Whac-A-Mole. Tic Tac Toe doesn’t have any type of score, just winners. The old typing game is probably going to be replaced by the new Space typing.
Fixes #75 
@RishuKumarCodes pls review.
> added hi score storage for games

- Client/src/pages/ProjectInfo.jsx
This PR adds skeleton loading UI for content being fetched from the GitHub API in the About page, while keeping static content immediately visible.
fixes: #182 
Changes Made:
Added skeleton loaders only for API-fetched data:
Repository description
README file link
Contributor cards (avatars, names, contribution counts)
Repository stats (stars, forks, language, dates)
Additional repo details (branch, license, watchers, size)
Used minimal skeleton components that match the final UI dimensions
Maintained all existing functionality and styling
Preserved all static text content without skeletons
Testing:
Verified skeleton appears only during API loading
Confirmed no layout shifts after data loads
Checked responsiveness across screen sizes
Ensured dark mode compatibility
The implementation …
> Updated: Add skeleton on about page. #182

- Client/src/pages/ProjectInfo.jsx
This PR adds Framer Motion-based hover and tap animations to the **“Open on GitHub”** button on the About page. The animation mimics the **"Start Studying"** button in the Timer section on the homepage, with no changes to existing styling or layout.
Fixes #263 
https://github.com/user-attachments/assets/c0ba9140-9300-4fc6-a2cb-a4bf65102335
https://github.com/user-attachments/assets/2547e116-c68d-45bf-96aa-438b3444c6a0
* Animation parameters used: `whileHover={{ scale: 1.03 }}`, `whileTap={{ scale: 0.97 }}`
* No impact on layout or functionality – purely UI enhancement
* Only the necessary component was updated – no unrelated file changes
> Added framer-motion animation to Open on GitHub button on About page

- Client/src/components/Sidebar.jsx
Description
Added a Friends button to the sidebar that redirects users to the /friends page, using the Users icon from lucide-react.
Related Issue
Fixes # 308
Changes Made
Imported Users icon from lucide-react.
Added SidebarLink for /friends route in the sidebar.
Ensured active state highlighting works with the animated indicator.
Sidebar with Friends Button:
Checklist
I have performed a self-review of my code.
My changes are well-documented.
I have tested the Friends button and confirmed it navigates to /friends.
No existing functionality is broken.
> add friends button in sidebar

- Client/src/components/stats/Leaderboard.jsx
The leaderboard on stats page showed the duration only in minutes. Edited that to show the results in days and hours as well.
Fixes #366 
- updated Leaderboard.jsx
> fix the time count in leaderboard

- Client/src/components/session/OtherRooms.jsx
This PR fixes the issue where the search box text was not visible in light mode. The fix ensures that the search input text color now adapts correctly with the theme.
Fixes #360 
- Updated search box input styling to use theme-based CSS variables for text color.
- Ensured compatibility with both light and dark modes.
- ✅ I have performed a self-review of my code.  
- ✅ Any dependent changes have been merged and published.
> fix: search box text color is now visible in all themes

- Client/src/components/Sidebar.jsx
This PR swaps the positions of the **Games** and **Friends** buttons as per issue #365.  
- The **Friends** button now appears below the **Stats** button.  
- The **Games** button is moved to the end of the navigation section.  
Fixes #365  
No other files were modified beyond what was required for this fix.
> [FIX]: #365 Swap the position of games and friends button 

- Client/src/components/home/notes/NotesComponent.jsx
This PR fixes the text color contrast issues in the UI. Specifically:  
- The **"Number of Notes"** text was blending with the background, making it difficult to read.  
- The **Title text** was also blending with the background, reducing visibility.  
Both have been updated with higher-contrast colors for better readability.  
Fixes #399 
- Verified that the updated colors meet accessibility contrast guidelines.
> [FIX]: #399 UI & Text Visibility in Notes Section

- Client/src/components/stats/ProfileCard.jsx
Fixed icons shrinking issue in profile card when adjacent text is too long by preventing icon resize.
Fixes #410
Before
After
> fix: #410 prevent icons from shrinking in profile card

- Client/src/components/stats/StudyStats.jsx
> issue #481 fixed

- Client/src/components/friendsSection/FriendsRequests.jsx
Decline button was not working on friend requests in session page 
as the request method used there was post and the method supposed to be used there was delete
Fixes #511
> fix: Decline button doesn't work on friend requests #511

- Client/src/pages/FriendsPage.jsx
- Client/src/pages/Settings.jsx
Fixed the naviagtion issue
Fixes #513 
Previously, 
- you create a new tab 
- go to site (eduhaven.online)
- go to stats (/stats)
- go to tools (/tools)
- go to settings (/settings?tab=basic-info)
- go to different setting tab (say account, then education & skills etc)
- then click back button, you be at the new tab page
Now,
- you create a new tab 
- go to site (eduhaven.online)
- go to stats (/stats)
- go to tools (/tools)
- go to settings (/settings?tab=basic-info)
- go to different setting tab (say account, then education & skills etc)
- then click back button, you be /tools endpoint
> Enhance searchParams to use replace option for better URL management

- Client/src/components/friendsSection/FriendsRequests.jsx
- Client/src/components/friendsSection/SentRequests.jsx
Changed the skeleton loading condition to only show when actually loading data, not when there are no requests
Added a "No pending friend requests" message when there are no requests but loading is complete
Fixes #530
> Removed Skeleton on No pending frd Requests

- Client/src/components/notes/NoteCard.jsx
Updated the dropdown ui
Fixes #656
> Refactor NoteCard component: streamline color picker and hover functionality

- Client/src/components/friendsPage/UserCard.jsx
- Client/src/queries/friendQueries.js
The UI updates immediately to reflect the current state of friend requests
Fixes #676
https://github.com/user-attachments/assets/6e0963d6-5ad1-4b90-be5a-3cdd81af5f96
> Add cancel request button to UserCard and update friend request state management

- Client/src/components/notes/note.css
The lists created in /notes page did not show bullet points or numbering for the items. So i fixed the part in css file that caused the error and now that part is functional now.
Fixes #667 
- updated notes.css
> Fix the bullet points not showing in notes

- Client/src/components/home/navBar/OnlineUsers.jsx
- Client/src/components/home/navBar/Slogan.jsx
Description
This PR hides the quote section (slogan) on smaller screens to reduce the navbar height and improve responsiveness. When the screen width is below 768px, the quote will not be shown.
Related Issue
Fixes #729
Changes Made
Added responsive logic to hide the quote when screen width is below 768px.
Used a useEffect hook to track window resizing and toggle the quote visibility.
Improved UI responsiveness and layout on smaller screens.
Screenshots or GIFs 
Checklist
Code is formatted with the project’s Prettier config provided in .prettierrc.
Only the necessary files are modified; no unrelated changes are included.
Follows clean code principles (readable, maintainable, minimal duplication).
All changes are clearly documented.
Code has been tested across all supported themes and …
> slogan hide

- Client/src/components/friendsPage/MainContent.jsx
- Client/src/components/friendsPage/TabNavigation.jsx
- Client/src/components/friendsPage/tabs/AllFriends.jsx
- Client/src/components/friendsPage/tabs/FriendRequests.jsx
- Client/src/components/friendsPage/tabs/SentRequests.jsx
- Client/src/components/friendsPage/tabs/SuggestedFriends.jsx
- Client/src/components/skeletons/FriendsSkeletonLoader.jsx
- Client/src/components/skeletons/UserCardSkeleton.jsx
This PR standardizes the layout across all tabs in the Friends page. The Suggested tab was used as the base design. Skeletons, card spacing, and alignment have been matched across Friend Requests, Sent Requests, and All Friends tabs. 
FIX: UI in friend's page. and skeleton. #657 
- Updated skeleton layout (removed borders, matched rows/columns with Suggested tab)
- Applied the Suggested tab layout to all Friends page tabs
- Added loader at the end
- Minor margin and spacing adjustments for visual consistency
> fix(ui): align skeleton and friends page tabs layout with suggestions tab layout

- Client/src/components/about/Hero.jsx
This PR removes the logo hover effect and the border radius
Fixes #750 
- Remove the border radius and hover effect from the logo
Before
After
> Fix: remove logo hover effect from about page

- CODE_OF_CONDUCT.md
- LEARN.md
- README.md
I updated discord link at 3 places in the README.md file
Fixes #788 
<br> <br/>
Locations in README
1. The banner image at the top
2. The line under the installation/setup section
3. The note near the end (“For any further queries, feel free to reach out on our [Discord] group.”).
And now its working fine...
> Update README.md with crct discord links

- Client/src/components/notes/NoteHeader.jsx
- Client/src/pages/Notes.jsx
This PR adds an active tab indicator and animation for the Notes page, specifically improving the user interface for navigating between "Notes", "Archived", and "Trash" tabs. This enhances clarity and user experience while switching tabs.
Fixes #774
- before
- after
> Add active tab indicator and animation to NoteHeader and Notes page

- Client/src/pages/Notes.jsx
- Server/Controller/NotesController.js
- Server/Routes/NotesRoutes.js
- Server/utils/Cloudnary.js
This PR improves image handling in the note editor  and removal workflow
---
Fixes #725  
---
- Replaced the old "Insert Image" button (which required a URL) with a **file selector** that supports uploading multiple images at once.  
- Fixed behavior where adding multiple images would **replace the previous one** — now multiple images are appended correctly.  
- Fixed image deletion: removing an image from a note now also **removes it from Cloudinary**, ensuring user privacy and freeing storage.  
---
_Add screenshots or a short recording of insert/remove behavior here_  
---
> fix insert image button and handle Cloudinary image removal

- Client/src/App.jsx
- Client/src/components/home/notes/BottomControls.jsx
- Client/src/components/notes/NoteEditor.jsx
- Client/src/pages/Notes.jsx
This PR implements full screen feature in notes card in home page
Fixes #773 
https://github.com/user-attachments/assets/9557e880-9f21-41e9-9053-9f1b6823ebb8
- [x ] Code is formatted with the project’s Prettier config provided in `.prettierrc`.
- [ x] Only the necessary files are modified; no unrelated changes are included.
- [ x] Follows clean code principles (readable, maintainable, minimal duplication).
- [ x] All changes are clearly documented.
- [ x] Code has been tested across all supported themes and verified against potential edge cases.
- [ x] Multiple screenshots or recordings are attached (if required).
- [ x] No breaking changes are introduced to existing functionality.
> Implemented full screen in notes card in home page

- Server/utils/sendMail.js
Sender name in mails received by users were appearing as "Eduahaven". Fixed it to be "Eduhaven".
Fixes #762 
Updated sendMail.js
- Renamed Eduahaven as Eduhaven
> Fix: sender name in mails

- Client/src/pages/PrivacyPolicy.jsx
Made the email a clickable link from a simple plain text, which on clicking will take to gmail with pre defined mail address in recipient field.
Fixes #804 
In PrivacyPolicy.jsx
Surrounded the email address with anchor tag and made it a hyperlink which would open in a new tab. Also added hover effect on the button.
https://github.com/user-attachments/assets/20fde8c8-d5df-4519-95cc-de101140a6b0
> Make email clickable with hover effect on Privacy page

- Client/src/components/home/notes/BottomControls.jsx
The download button on home page for notes did not work. So i added functionality to download those notes in md files. 
Fixes #775 
-  Updated `Client/src/components/home/notes/BottomControls.jsx`
[Demo Video](https://jumpshare.com/s/Wod75F1ugpAI4RJgBswN)
> add download functionality to home notes tab

- Server/Middlewares/usernameHandler.js
- Server/index.js
This PR fixes a critical server crash issue caused by the `handleMissingUsernames` middleware.  
Previously, the server attempted to call `.split()` on `user.Email` without verifying its existence.  
If a user document was missing the `Email` field, this resulted in a `TypeError` during startup, preventing the server from running.  
The fix adds proper guard checks to ensure `Email` exists and is valid before calling `.split()`.  
If the field is missing, the user is safely skipped with a warning log instead of crashing the server.  
Fixes #834 
update workflow would look like:
This fix ensures that server startup is robust even if old or malformed user records exist in the database.  
It improves stability without altering the normal username assignment logic.
> Fix: Prevent server crash when Email field is missing in user documents

- Client/src/components/home/navBar/PinnedLinks.jsx
To fixed the motion stacking context issue during hovering over link row items, removed the framer motion entairly from PinnedLinks component and to reach similer effects/transition used native tailwind CSS utility classes.
Fixes #816 
https://github.com/user-attachments/assets/759abae4-5267-4b88-bc3d-5626f0d1c3d4
> Fix/Framer Motion Stacking Context Issue from PinnedLinks Dropdown Menu

- Client/package-lock.json
- Client/package.json
- Client/src/components/session/CreateRoomModal.jsx
- Client/src/components/session/RoomCard.jsx
- Client/src/components/session/YourRooms.jsx
- Server/Controller/SessionRoomController.js
- Server/Model/SessionModel.js
- Server/Routes/SessionRoomRoutes.js
- Server/index.js
This PR introduces **Private Study Rooms with Join Status API** support. It ensures the join/request logic for both private and public study rooms is backend-driven, eliminating inconsistencies and providing clear UI feedback.
Fixes #811
* **Backend**
* **SessionRoomController.js**
* Added `getJoinStatus` method to return the user’s join status (`member`, `pending`, or `none`).
* **SessionRoomRoutes.js**
* Registered a new route `GET /session-room/:id/join-status` secured with `authMiddleware`.
* **Frontend**
* **RoomCard.jsx**
* Refactored button logic to fetch join status from backend.
* Button text and actions now update dynamically based on backend response:
* "Enter Room" if member.
* "Request Sent" if request is pending.
* "Request Join" if not a member.
* "Join" / "Already Joined" …
> feat: Implement Private study rooms

- Client/src/components/home/notes/NotesComponent.jsx
This PR fixes the behavior where a new note gets added at the end page, but after saving it in the database, the app incorrectly navigated back to the first page.  
Now, the newly created note will remain visible on the last page after saving.
Fixes #767 
N/A
> Fix note pagination

- Client/src/components/AdCard.jsx
- Client/src/components/stats/Leaderboard.jsx
- Client/src/components/stats/MonthlyLevel.jsx
- Client/src/components/stats/StudyStats.jsx
- Client/src/pages/Stats.jsx
This PR improves the stats page’s auth/loading flow to prevent premature “not logged in” or error states and introduces loading skeletons during data fetches. It centralizes loading in child components, adds a fetched guard before showing NotLoggedInPage, and uses optional chaining to avoid crashes from undefined props.
Bug: fix UI in stats page #327
Review the loading/exit conditions in `Stats.jsx` and the new skeleton logic in child components.
> Stats: refine auth/loading handling and add loading skeletons

- Client/src/components/session/CreateRoomModal.jsx
- Client/src/components/session/RoomCard.jsx
- Server/Controller/SessionRoomController.js
- Server/Routes/SessionRoomRoutes.js
Fix private room flow: dynamic buttons + cancel request endpoint
- Add “Make this room private” in create modal; send `isPrivate`.
- Dynamic room actions: Request Join, Cancel Request, Enter Room, Join.
- Join before navigate; add `POST /session-room/:id/cancel-request`.
- Auto-refresh join status (poll + on tab focus).
Fixes #861
- Backend: add cancel endpoint; ensure private creators in `members`; join/join-status solid.
- Client: `CreateRoomModal.jsx` checkbox; `RoomCard.jsx` dynamic buttons, cancel, polling.
> fixed join session bug

- Client/src/components/friendsPage/tabs/SuggestedFriends.jsx
Closes https://github.com/EduHaven/EduHaven/issues/898
> The inline style for the scrollable div in SuggestedFriends.jsx no longer sets a fixed height, allowing it to adapt dynamically. This improves layout flexibility and prevents potential overflow issues on different screen sizes.
- Removed extra Scrollbar
- Now navigated- https://eduhaven.online/friends?tab=findFriends will get only one scrollbar
> Remove Extra scrollable div

- Client/src/components/about/Hero.jsx
On the **About page**, the following layout issues were observed:
- The **website logo** overlaps with the **“Our Open-Source Work”** section.  
- The **Feedback button** and **README file link** were positioned too close to each other, affecting readability and spacing on smaller screens.
**resolve**: #905
-  **Reduced the logo size** to maintain proper spacing with the “Our Open-Source Work” heading.  
- **Hid the logo on smaller screens** (`hidden md:block`) to improve layout responsiveness.  
- 
- The About page now maintains proper alignment across all screen sizes.  
- Overlapping issues are resolved, and the layout looks clean and responsive.
**Before:**  
**After:**  
https://github.com/user-attachments/assets/cb902341-0a24-438f-a0d2-d23a588b020a
> Fix: Logo Overlap and Layout Alignment on About Page
