- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/assign-bot.yml
fixes: #3 
Description:
1. GitHub bot that automatically assigns an issue when someone comments "bot/assign"
2. Pull Request (PR) template appears automatically whenever someone opens a pull request in this repository.
> Feature: added GitHub bot, and template for PR.

- README.md
Updated readme file to make easier for newcommers to get started.
Fixes #2 
added details about the project, setup process, contributing guidlines and many more.
> Update : readme file

- Client/src/components/Layout.jsx
Fixed Sidebar with height 100vh
Fixes #<issue_number>
- [ Layout.jsx] Updated ...
> Fixed sidebar

- Client/package-lock.json
- Client/package.json
- Client/src/pages/studyRoom/AiChatbot.jsx
- Client/src/pages/studyRoom/StudyRoom.jsx
Introduced Chatting feature you can now ask questions to chatbot. 
none
- added Icon in navbar to access chatbot.
- added popup-dialog box to chat with AI.
> Freature: added AI Chatbot

- Client/src/pages/studyRoom/CalendarComponent.jsx
I have added a new section under the calendar where upcoming two events will be shown and resolved issue #30 
Fixes #30
> added upcoming events section CalendarComponent.jsx

- Client/src/Auth/Authenticate.jsx
- Implemented a Google Login button for third-party authentication.
- Added a 'Remember Me' checkbox to persist user sessions.
- Enhanced toggle button styling for 'Sign Up' and 'Log In.'
- Improved UI for password field with a Show/Hide toggle.
> Update: implemented google-Signup/Login page

- Client/src/pages/studyRoom/AiChatbot.jsx
> Fix: AI Chat UI and added functionalities

- Client/package-lock.json
- Client/package.json
- Client/src/pages/ProfilePage.jsx
- Server/Controller/UserController.js
- Server/Routes/UserRoutes.js
> Email bug fixed

- Client/src/pages/studyRoom/NotesComponent.jsx
> added new UI for Notes

- Client/src/App.jsx
- Client/src/components/Layout.jsx
- Client/src/pages/ProjectInfo.jsx
added page to share all details of our project using github api.
> Feature: added Project-details page

- Client/index.html
- Client/src/App.jsx
- Client/src/components/Layout.jsx
- Client/src/index.css
- Client/src/pages/Anaylitics/Anaylitics.jsx
- Client/src/pages/ProjectInfo.jsx
- Client/src/pages/studyRoom/AiChatbot.jsx
- Client/src/pages/studyRoom/NotesComponent.jsx
- Client/src/pages/studyRoom/StudyRoom.jsx
- Client/src/pages/studyRoom/StudyStats.jsx
- Client/src/pages/studyRoom/TimerComponent.jsx
- Client/tailwind.config.js
Now, notes can be added, deleted and updated. 
Fixes #<issue_number>
> fix: Notes functionality

- Client/src/App.jsx
- Client/src/pages/homeDashboard/Home.jsx
- Client/src/pages/homeDashboard/TimerComponent.jsx
- Client/src/pages/homeDashboard/TimerStats.jsx
- Client/src/pages/stats/Stats.jsx
- Client/src/pages/stats/StudyStats.jsx
- Client/src/pages/stats/Test.jsx
- Server/Model/StudySession.js
- Server/Model/UserModel.js
- Server/Routes/TimerSessionsRoutes.js
- Server/index.js
- Server/utils/TimerStatsCalculator.js
- Server/utils/streakUpdater.js
Fixes #35 
- Added "Take a break" feature.
- Added connection to backend.
- The timer only gets saved if it runs more than 1 minute, so to prevent unnecessary accidental timers entering to DB.
- added functionality to view the data by hourly/ daily/ weekly or monthly
- The total study-time, Average study-time and maximum is calculated in frontend.
- the DB stores each session seprately, and stores duration in minutes. 
- the DB deletes the timer-data if it's older than 5 months. 
- The streak and max streak is calculated. 
**Timer stats Graph:**
- **I will be adding the Leaderboard Feature, Rank, Streak, and Max streak in upcoming PR.**
> added functionality to Timer and Timer-analitics.

- Client/src/components/Layout.jsx
- Client/src/pages/homeDashboard/CalendarComponent.jsx
- Client/src/pages/homeDashboard/Home.jsx
- Client/src/pages/homeDashboard/NotesComponent.jsx
- Client/src/pages/homeDashboard/TimerComponent.jsx
- Client/src/pages/homeDashboard/TimerStats.jsx
- Client/src/pages/homeDashboard/TodoComponent.jsx
- Client/src/pages/stats/ProfileCard.jsx
> enhanced UI

- Client/package-lock.json
- Client/package.json
- Client/src/pages/homeDashboard/CalendarComponent.jsx
- Client/src/pages/homeDashboard/GoalsComponent.jsx
- Client/src/pages/homeDashboard/Home.jsx
- Client/src/pages/homeDashboard/NotesComponent.jsx
- Client/src/pages/homeDashboard/SetGoals.jsx
- Client/src/pages/profileSettings/BasicInfo.jsx
- Client/src/pages/profileSettings/ProfileSettings.jsx
- Client/src/pages/stats/Achievements.jsx
- Client/src/pages/stats/Badges.jsx
- Client/src/pages/stats/Goals.jsx
- Client/src/pages/stats/Leaderboard.jsx
- Client/src/pages/stats/MonthlyLevel.jsx
- Client/src/pages/stats/ProfileCard.jsx
- Client/src/pages/stats/Stats.jsx
- Client/src/pages/stats/StudyStats.jsx
- Client/src/styles/ReactCustomCalendar.css
Updated UI in stats, home page, profile edit settings page, added features in input field of todo
- now the Goals input fields can take input of the deadline date and time, toggle repeat on/off, set reminder.
> UI fixes and frontend Goals section work 

- Client/package-lock.json
- Client/package.json
- Client/src/App.jsx
- Client/src/Auth/Authenticate.jsx
- Client/src/Auth/Signout.jsx
- Client/src/Auth/Verifyotp.jsx
- Client/src/pages/homeDashboard/TodoComponent.jsx
- Server/.env
- Server/Controller/UserController.js
- Server/Middlewares/authMiddleware.js
- Server/Routes/UserRoutes.js
- Server/package-lock.json
- Server/package.json
- Server/utils/IsAuth.js
- Server/utils/sendMail.js
> add otp base login

- Client/src/pages/homeDashboard/AiChatbot.jsx
> Fix Ai ChatBot error

- Server/Controller/UserController.js
- Server/Routes/UserRoutes.js
- Server/package-lock.json
- Server/package.json
- Server/utils/Cloudnary.js
> 	 Add Upload profile when user Signup Only In Backend

- Client/src/components/Layout.jsx
- Client/src/pages/Sessions/Friends.jsx
- Client/src/pages/Sessions/Sessions.jsx
- Client/src/pages/profileSettings/Friends.jsx
- Client/src/pages/profileSettings/ProfileSettings.jsx
- Server/Controller/FriendsController.js
- Server/Controller/UserController.js
- Server/Model/UserModel.js
- Server/Routes/EventRoutes.js
- Server/Routes/FriendsRoutes.js
- Server/Routes/NotesRoutes.js
- Server/Routes/ToDoRoutes.js
- Server/index.js
- Server/utils/TimerStatsCalculator.js
User can now add friends, remove friends and see the friends list. 
add-friends-feature: under `/study-room`
friends-list and remove-friends list under ` profile/friends`
I'll also be creating a conformation mesage so only after accepting request, user can be friends.
> worked on friends feature

- Client/index.html
- Client/src/components/Layout.jsx
- Client/src/components/ThemeToggle.jsx
- Client/src/index.css
- Client/src/pages/Sessions/friendsSection/SentRequests.jsx
- Client/src/pages/Sessions/friendsSection/SuggestedFriends.jsx
- Client/src/pages/homeDashboard/CalendarComponent.jsx
- Client/src/pages/homeDashboard/GoalsComponent.jsx
- Client/src/pages/homeDashboard/Home.jsx
- Client/src/pages/homeDashboard/NotesComponent.jsx
- Client/src/pages/homeDashboard/SetGoals.jsx
- Client/src/pages/homeDashboard/TimerComponent.jsx
- Client/src/pages/homeDashboard/TimerStats.jsx
- Client/src/pages/homeDashboard/eventPopup.jsx
- Server/Controller/FriendsController.js
> worked on light-dark theme

- License.md
I have created the LICENSE file using the MIT License to ensure this project is open-source and clearly states the terms of use and distribution. This issue tracks the addition and commit of the MIT License to the repository. Feel free to review the license file and suggest any changes if needed.
> Add MIT License to the Project

- Client/src/components/home/navBar/AiChatbot.jsx
- Client/src/index.css
- Server/package-lock.json
- Server/package.json
Fixes the issue where the shadow (glow) of the Ask AI button and AI chat panel remained a fixed purple color, regardless of the selected theme. The shadow color now adapts based on the active theme using a CSS variable (--shadow-rgb), ensuring visual consistency across themes.
Fixes #123 
- Replaced hardcoded shadow color with --shadow-rgb in AiChatbot.jsx
- Defined --shadow-rgb for each theme in index.css to match the theme's accent color
- I have performed a self-review of my code.
- My changes are well-documented.
- I have tested the fix across all supported themes.
- Any dependent changes have been merged and published.
> Fix: make Ask AI button and chat panel shadow color theme-based

- Client/src/components/home/goalsAndNotes/NotesComponent.jsx
Prevent sync when title or content is missing. Show "Title is required" and "Content is required" errors if the user leaves them empty .
Fixes #133
> fix(sync): prevent sync with empty title/content and show required field errors

- Client/src/components/stats/ProfileCard.jsx
This PR fixes the issue of the endpoint leading to the /profile route. There is no /profile route so the 404 page shows up. The correct route is /settings. I have made the needed changes to lead to the correct route.
Fixes #164 
https://github.com/user-attachments/assets/e2562252-d33a-43cc-af19-3a4e4304c14b
Nothing. I would request @RishuKumarCodes to kindly review this PR.
> changed redirect endpoint to /settings

- Client/src/App.jsx
- Client/src/Auth/Login.jsx
- Client/src/Auth/SignUp.jsx
- Client/src/Auth/Signout.jsx
- package.json
Replaced ⁠ alert() ⁠ messages with user-friendly toast notifications in authentication components to improve user experience.
---
Fixes #169
---
•⁠  ⁠[x] Updated *SignUp* component to use toast notifications instead of ⁠ alert() ⁠
•⁠  ⁠[x] Updated *Login* component to use toast notifications instead of ⁠ alert() ⁠
•⁠  ⁠[x] Updated *Signout* component to use toast notifications instead of ⁠ alert() ⁠
•⁠  ⁠[x] Added ⁠ react-toastify ⁠ dependency
•⁠  ⁠[x] Added ⁠ ToastContainer ⁠ to ⁠ App.js ⁠ for global toast support
•⁠  ⁠[x] Implemented success and error toast messages for all authentication flows
---
---
•⁠  ⁠[x] I have performed a self-review of my code  
•⁠  ⁠[x] My changes are well-documented  
•⁠  ⁠[x] I have added tests that prove my fix is effective or that my feature works  
•⁠ …
> feat: replaces alerts with toast, added toast to signup, login and signout 

- Client/src/components/home/timerComponent/StudyTimer.jsx
Implemented a comprehensive auto-save mechanism to prevent study timer data loss when users navigate away, refresh the page, or switch tabs. The timer now automatically saves progress every 30 seconds and provides robust protection against all data loss scenarios while maintaining efficient database usage.
Fixes #132
**Key Features:**
- **Never lose data**: Multiple save mechanisms (auto-save + event-based)
- **Efficient**: Only saves every 30 seconds with smart progress tracking
- **User-friendly**: Clear warnings and confirmations before data loss
- **Robust**: Handles network failures, browser crashes, and all navigation scenarios
- **Non-breaking**: Zero changes to existing UI/styling - only functionality improvements
**Edge Cases Covered:**
- Browser refresh/close with warning dialog …
> 🛡️ Fix: Implement robust auto-save to prevent study timer data loss

- Client/src/components/home/calenderComponent/CalendarComponent.jsx
- Client/src/components/home/calenderComponent/eventPopup.jsx
- README.md
- Server/Controller/EventController.js
- Server/Model/EventModel.js
- Server/Routes/EventRoutes.js
**DRAFT – Ready for Initial Review** This PR implements a comprehensive security fix for the Calendar Event system as requested in issue #71. The update resolves the critical privacy vulnerability where all users could see every other user's calendar events, implementing proper user-based access control and authentication.
I believe this implementation covers all the security requirements from the issue, but would appreciate maintainer review to ensure the privacy controls are robust before converting to a full PR.
Fixes #71
* **Database Schema Update**: Added `createdBy` field to `EventModel.js` to associate events with users
* **Authentication Middleware**: Applied `authMiddleware` to all event routes in `EventRoutes.js`
* **Access Control Logic**: Updated all controller methods in …
> fix: restricting events visibility to respective user

- Client/src/components/ConfirmLogoutModal.jsx
- Client/src/components/home/calenderComponent/eventPopup.jsx
- Client/src/components/home/goalsAndNotes/GoalsComponent.jsx
- Client/src/components/session/CreateRoomModal.jsx
- Client/src/components/session/YourRooms.jsx
- Client/src/index.css
There was no background blur and dim black color in the 'add event' popup. Hence, the popup properly was not separated from the background.
Added Background blur in event pop-up. 
Additionally, added defensive check for todos array to prevent runtime errors when undefined or invalid. Also updated background overlay for improved UI clarity.
Fixes #227 
Added Background overlay in event pop-up for UI imrovement. 
Additionally, added defensive check for todos array to prevent runtime errors when undefined or invalid.
@RishuKumarCodes  Kindly let me know if any changes.
> Background blur in event pop-up

- Client/src/index.css
- Client/src/pages/ProjectInfo.jsx
This pull request addresses the issues reported in #182 by fixing bugs and improving the functionality to enhance overall stability and user experience.
Fixes #182
All changes follow project guidelines and maintain backward compatibility.
> Implemented about page loading skeleton

- Client/src/components/home/timerComponent/StudyTimer.jsx
Fixes #235 . Update on start timer
I modified the StudyTimer.jsx component to make the button animations smooth and consistent with the BreakTimer.jsx component.
Added Framer Motion Import.
Replaced CSS-based Button with Framer Motion Button
Simplified Button Content Structure
Updated Reset Button
Framer Motion provides hardware-accelerated, smooth animations that are optimized for performance, while CSS transforms can cause jitter due to layout recalculations.
Consistent Scale Values: Changed from hover:scale-105 active:scale-95 to whileHover={{ scale: 1.03 }} whileTap={{ scale: 0.97 }} to match the BreakTimer's smooth scaling.
> Smooth animation for Start Studying button 

- Client/src/components/home/goalsAndNotes/DeadlinePickerModal.jsx
- Client/src/components/home/goalsAndNotes/GoalsComponent.jsx
- Client/src/components/home/goalsAndNotes/SetGoals.jsx
- Client/src/components/settings/UpdateButton.jsx
Fixed the profile button to adapt  theme and be at opacity 0.5 when disabled.
Fixes #244 
https://github.com/user-attachments/assets/8930840f-8b8c-42fa-a585-16787ae69ebb
> fix: Updated the profile buttons.

- Client/src/components/stats/Achievements.jsx
- Client/src/components/stats/Badges.jsx
- Client/src/components/stats/Goals.jsx
- Client/src/components/stats/Leaderboard.jsx
- Client/src/components/stats/MonthlyLevel.jsx
- Client/src/components/stats/StudyStats.jsx
- Client/src/components/ui/dropdown-menu.jsx
- Client/src/pages/Stats.jsx
@RishuKumarCodes 
I have changed all the hard codes css values with the variable. Now on every component in the Stats matches with the active theme.
Fixes #125 
- Updated all the component used in /pages/stats.jsx
- Only used available Custom variables.
Kindly review the changes at your convenience.
> fix : stats page theme

- Client/src/Auth/Login.jsx
- Client/src/Auth/SignUp.jsx
Added Password strength checker which displays how strong the password is .
Fixes #120
> feat: add password strength indicator  in Login and SignUp components

- Client/src/components/home/goalsAndNotes/NotesComponent.jsx
- Added an empty, box with a plus (+) icon in the notepad section for creating new notes.
- Enabled immediate editing of the title and content fields for new notes upon creation.
- Implemented support for creating and displaying multiple notes in a list format.
- Fixed the delete button functionality to properly remove notes.
Fixes #246
<div style="display: flex; gap: 16px;">
</div>
> FIX: Title input and Notepad UI

- Client/src/components/session/OtherRooms.jsx
- Client/src/components/session/RoomCard.jsx
> Revert "Added loading skeleton for sessions cards"

- Client/src/App.jsx
- Client/src/components/friendsPage/MainContent.jsx
- Client/src/components/friendsPage/TabNavigation.jsx
- Client/src/components/friendsPage/UserCard.jsx
- Client/src/components/friendsSection/SuggestedFriends.jsx
- Client/src/main.jsx
- Client/src/pages/FriendsPage.jsx
- Server/Controller/FriendsController.js
- Server/Routes/FriendsRoutes.js
On the sessions page, if the suggested friends are more than 15, only first 15 users are shown and a link to open a new page (/friends) is shown. On clicking the link, the user is redirected to /friends where he/she can see all suggested friends, incoming friends requests, sent requests and all friends. they can also manage those requests from the page.
Fixes #233 
- added new folder friendsPage in components section that handles various UI components for the page.
- updated Session.jsx to add a condition to handle >15 suggested friends.
-  added friends page.jsx file to show the /friends page to users.
- updated friendController.js to handle cancel sent requests.
the below image is a sample to show the link that redirects the user. In functionality, this will be visible only when …
> added Friends page (/friends)

- Client/src/components/home/calenderComponent/CalendarComponent.jsx
- Client/src/components/settings/BasicInfo.jsx
- Client/src/components/stats/ProfileCard.jsx
Updated Hover effects
Fixes #268 & #269
> UI fix in settings and stats

- Client/src/components/stats/StudyStats.jsx
The dropdown menu in the StudyStats component previously had a visible white  border that clashed with the dark theme and distracted from the surrounding  analytics UI. Updated the DropdownMenuContent to use Tailwind's `border-none`  class, removing the border while preserving spacing and alignment.
This change improves visual consistency across components, aligns with the  design intent of a minimal dark interface, and enhances focus on menu options  instead of the container outline.
Fixes #<issue_number>
Remove white border on dropdown #297
Just added border-none class in DropDownMenuContent  in StudyStats.jsx file
> style: remove border from dropdown menu content PR#297

- Client/src/pages/Stats.jsx
- Server/package-lock.json
- Server/package.json
Description
This PR removes the Achievements section from the Stats component to simplify the UI and improve clarity.
Related Issue
Fixes # 296
Changes Made
Removed the Achievements section from the Stats component.
Updated layout to ensure proper alignment after removal.
Checklist
I have performed a self-review of my code.
My changes are well-documented.
I have tested the updated UI to ensure correct layout and responsiveness.
Any dependent changes have been merged and published.
Additional Notes
This change is focused purely on UI cleanup and does not affect backend logic or data.
> remove achievements section from stats

- Client/src/pages/ProjectInfo.jsx
This PR focuses on improving the UI icons for better visual clarity and consistency across the application.
Fixes # 206
All icon-related changes have been made while ensuring alignment with the overall design guidelines.
> Icon improvement inside project-details

- Client/src/components/settings/Account.jsx
- Client/src/pages/ProjectInfo.jsx
- Server/Controller/UserController.js
- Server/Routes/UserRoutes.js
- Server/package-lock.json
- Server/package.json
Description
Added a Privacy Policy link to the right panel of the About page, which redirects users to the /privacy page. Also added a © 2025 Eduhaven footer text below the link for branding and legal purposes.
Related Issue
Fixes #330 
Changes Made
Added Privacy Policy link in the About page right panel.
Linked the Privacy Policy link to /privacy route.
Added © 2025 Eduhaven text below the link.
Screenshots or GIFs (if applicable)
Checklist
I have performed a self-review of my code.
I have tested the link navigation to ensure correct routing.
Any dependent changes have been merged and published.
Additional Notes
No breaking changes introduced. The update is purely UI and navigational enhancement for better accessibility and compliance.
> Privacy policy added 

- Client/src/components/games/2048/Game2048.jsx
- Client/src/components/games/2048/Game2048.module.css
This pull request fixes the navbar positioning in the 2048 game component. The navbar now remains fixed at the top of the screen regardless of scroll position or screen size, improving navigation and user experience.
Fixes #142
- Modified the Game2048.module.css file to add proper spacing for the fixed navbar
- Added responsive adjustments for different screen sizes
- Created proper container hierarchy to ensure content doesn't overlap with the navbar
Before: Navbar would scroll with the content 
After: Navbar stays fixed at the top of the screen
The fix ensures proper spacing on both mobile and desktop viewports.
> fixed navbar issue

- Client/src/components/stats/Goals.jsx
Fixes #324 
https://github.com/user-attachments/assets/8307723e-d50f-472a-bdf9-43e57b9eccf3
I have fixed the issue in the stats page and now it's working as expected:
@RishuKumarCodes pls review I have done changes as you asked :)
> fixed issue in stats page

- Server/Database/Db.js
Refactored the ConnectDB function to remove the mix of .then() and async/await. This ensures proper error handling and consistent asynchronous code style using try...catch with await.
Fixes #390 
- [Replaced .then() inside ConnectDB with await ]
Before
```js
export const ConnectDB = async () => {
const uri = process.env.MONGODB_URI;
try {
mongoose.connect(uri, ).then(()=>{
console.log("Connected to Database")
})
} catch (error) {
console.log("Error: ", error.message);
}
}
```
After
```js
export const ConnectDB = async () => {
const uri = process.env.MONGODB_URI;
try {
await mongoose.connect(uri, );
console.log("Connected to Database");
} catch (error) {
console.log("Error: ", error.message);
}
}
```
-  I have performed a self-review of my code.
I’ll be checking other parts of the codebase …
> Refactor Promise .then to await in ConnectDB Class

- README.md
Added Discord Link to the README file.
Fixes #415
> add discord link to README.md

- Client/src/components/settings/EducationAndSkills.jsx
Fix clear button so the skill and interest clears upon clicking it
Fixes #412 
https://github.com/user-attachments/assets/2070ff15-fab0-496f-b431-df7e6b84c8a2
> clear buttons clears the skill/interests

- Client/src/components/home/calenderComponent/AllEventsPopup.jsx
- Client/src/components/home/calenderComponent/eventPopup.jsx
- Server/Controller/EventController.js
- Server/Middlewares/authMiddleware.js
fix: update error handling, add input validation with toasts, fix fetch typo, and include headers for delete/save
Fixes #342 
- Updated error handling (400 → 500)
- Added input validation with toasts (create/update events)
- Fixed fetch typo
- Added headers for delete/save events
> fix: update error codes to 500, add input validation with toasts, fix fetch typo, and add headers for delete/save events

- Client/src/components/games/sudoku/Sudoku.jsx
- Client/src/components/games/sudoku/Sudoku.module.css
This PR improves the UI of the Sudoku game to make it more user-friendly and visually clear. Previously, the boxes and lines were not visible, colors were unclear, and there was no distinction between pre-filled numbers and user inputs.  
Nor the UI was matching with any other games that was present apart from Sudoku.
Fixes #406 
*Before:*
*After:*
https://github.com/user-attachments/assets/a7d18b9b-dbde-45b7-b548-533728a5fecc
*Dark Default*
*Coral Reef*
- The UI has been tested with multiple themes to ensure clear visibility and a consistent experience.  
- The game interface now aligns visually with other games like Tic-Tac-Toe for a cohesive design.
> [FIX]: #406 UI of Sudoku game 

- Client/src/components/settings/EducationAndSkills.jsx
Add Enter key functionality to add skills and interests
Fixes #432
> Add Enter key functionality to add skills and interests

- Client/src/components/stats/StudyStats.jsx
- Client/src/pages/Stats.jsx
- Server/Controller/UserController.js
- Server/Routes/EventRoutes.js
- Server/utils/streakUpdater.js
Update the current streak and max streak from static to dynamic(functional).
Fixes #172
Updated Stats.jsx to ensure current streak and max streak values are correctly retrieved and displayed.
Normalized data mapping for both current user and other users to avoid null/undefined issues.
Added safe fallbacks (?? 0) for all numerical stats, ensuring they display 0 instead of blank.
Improved consistency in userStats object between currentUser and fetched user flows.
Enhanced error handling & logging for easier debugging.
> Fix Stats Component: Properly Display Current & Max Streak + Improve Data Mapping

- Client/src/components/stats/ProfileCard.jsx
- Server/Controller/UserController.js
- Server/Model/UserModel.js
- Server/Routes/UserRoutes.js
Implemented kudos logic and toast notifications:
Fixes #306
> adds kudos functionality

- Client/src/components/stats/ProfileCard.jsx
- Server/Controller/UserController.js
Fixed the syntax issue in the usercontroller
Fixes #451
> fix syntax error

- Client/src/components/friendsPage/TabNavigation.jsx
- Client/src/components/settings/Sidebar.jsx
- Client/src/pages/FriendsPage.jsx
- Client/src/pages/Settings.jsx
Fixes the navigation between settings and friends page
> Refactor to manage active tabs

- Client/src/components/home/goals/GoalsComponent.jsx
Added rotate and transition property to the icon
Fixes #489
> added rotation and transition

- Client/src/components/NotLogedInPage.jsx
- Client/src/components/gameRoomComponents/GameRoom.jsx
- Client/src/components/landingPage/CTASection.jsx
- Client/src/components/landingPage/GoalsAndEvents.jsx
- Client/src/components/landingPage/HeroSection.jsx
- Client/src/components/landingPage/MakeFriends.jsx
- Client/src/components/landingPage/NavBar.jsx
- Client/src/components/landingPage/StudyRoom.jsx
- Client/src/pages/NoteNest.jsx
Added responsiveness in landing page , pagenotfound, game, notes
Fixes #470
https://github.com/user-attachments/assets/070db93e-7434-41e9-8901-5f5ee23d1ce5
> Added Responsiveness

- Client/src/components/home/goals/GoalsComponent.jsx
Add optimistic updates for todo actions with toast notifications, now the ui gets updated first then calls the api and in case of any error, rollbacks the change
Fixes #508
> Add optimistic updates for todo actions with toast notifications

- Client/src/components/friendsPage/UserCard.jsx
> Revert "fix: friends-page-button-alignment #501"

- Client/src/components/friendsSection/FriendsRequests.jsx
- Client/src/components/friendsSection/SentRequests.jsx
> Revert "Removed Skeleton on No pending frd Requests"

- Client/src/components/stats/ProfileCard.jsx
- Server/Controller/UserController.js
* The `getUserDetails` controller now spreads the user object directly into the response, instead of nesting it under a `user` key. This affects all return statements in the controller
Fixes #<issue_number>
> Fix user data retrieval

- Client/package-lock.json
- Client/package.json
- Client/src/components/sessionRooms/VideoGrid.css
- Client/src/components/sessionRooms/VideoGrid.jsx
- Client/src/components/sessionRooms/VideoPlayer.css
- Client/src/components/sessionRooms/VideoPlayer.jsx
- Client/src/hooks/WebRTC/WebRTCConnection.jsx
- Client/src/pages/SessionRoom.css
- Client/src/pages/SessionRoom.jsx
- Client/src/services/SFUService.js
- README.md
- SETUP_GUIDE.md
- Server/Controller/AuthController.js
- Server/Socket/socket.js
- Server/index.js
- Server/package-lock.json
- Server/package.json
- Server/sfu/Room.js
- Server/sfu/RoomManager.js
- Server/sfu/config.js
- Server/sfu/mediasoupServer.js
- Server/utils/sendMail.js
- docs/SFU_IMPLEMENTATION.md
Implements a complete **Selective Forwarding Unit (SFU)** architecture to replace the previous P2P mesh topology that failed with 3+ participants. This provides scalable, real-time video calling for study sessions using mediasoup and enhanced UI components.
**Key Achievement**: Transforms video calling from a 2-user limitation to supporting multiple participants efficiently with professional UI design.
Fixes #196  - Implement SFU for scalable video calling
> feat: Implement SFU-based video calling with mediasoup for scalable multi-user sessions

- Client/src/components/stats/ProfileCard.jsx
Adds smooth animation and consistency with color scheme
Fixes #408
> add animated popup and improved friend list display

- Client/src/components/settings/BasicInfo.jsx
- Client/src/components/settings/EducationAndSkills.jsx
- Client/src/components/settings/Sidebar.jsx
- Client/src/contexts/UserProfileContext.jsx
- Client/src/pages/Home.jsx
Add reminders to complete profile
Fixes #559
> Add profile completion checks and notifications in settings and home components

- Client/src/components/stats/ProfileCard/ProfileCard.jsx
Make sure to conditional render that empty div
Fixes #577
> fix the blob thing

- Client/package-lock.json
- Client/src/App.jsx
- Client/src/components/Sidebar.jsx
- Client/src/components/chats/chatwindow.tsx
- Client/src/components/chats/userlist.tsx
- Client/src/pages/Chats.jsx
Added the Chat page.
Fixes #561 
Added - 
1)componenets  - userlist and chatwindow
2) chat page
- [ x] I have performed a self-review of my code.
- [ x] My changes are well-documented.
- [ x] Any dependent changes have been merged and published.
> Created Chat page

- Client/src/pages/NoteNest.jsx
Description
This PR introduces major enhancements to our experimental Notes feature, inspired by Google notes.
Key improvements include:
Ability to create and manage multiple notes.
Each note supports adding Text, Image, Drawing, and Mind Map.
Drawing and Mind Map features, previously separate, have now been merged into a single unified note.
UI styled to closely match the overall website theme and maintain consistency.
Notes are saved in localStorage to ensure data persistence without backend dependency for now.
This enhancement provides a more user-friendly, cohesive experience for managing different types of content inside a single note.
Related Issue : Fixes #487 
Changes Made
Added support for creating multiple notes.
Integrated Text, Image, Drawing, and Mind Map into one note. …
> NoteNest Improvements - Notes Feature 

- Client/package-lock.json
- Client/package.json
- Client/src/pages/Chats.jsx
Resizable panels in chat section
Fixes #596
> Add react-resizable-panels for adjustable chat layout

- Server/Middlewares/ratelimit.middleware.js
- Server/Routes/AuthRoutes.js
- Server/Tests/authRateLimiter.test.js
**This PR improves security for authentication routes by adding a _per-IP + per-user rate limiter_ using `rate-limiter-flexible`  and ` express-rate-limiter`.
It helps protect against brute-force, credential stuffing, and _DoS_ attacks that target login endpoints.**
**- Added `rate-limiter-flexible` and ` express-rate-limiter` dependency.**
**- Implemented IP-based rate limiting (10 attempts per 5 min).**
**- Implemented user-based rate limiting (5 failed attempts per 15 min).**
**- Custom JSON error response with _retryAfter_ time for client-side handling.**
**- Applied _middleware_  to POST `/login` and `/signup` (to avoid blocking non-sensitive routes).**
**- Brute force mitigation → blocks attackers after repeated attempts.**
**- Credential stuffing defense → per-user limiter prevents …
> 🚀 Add Advanced Rate Limiting for Auth Routes 

- Server/Controller/UserController.js
- Server/Routes/AuthRoutes.js
- Server/Routes/EventRoutes.js
- Server/Routes/NotesRoutes.js
- Server/Routes/StudySessionRoutes.js
- Server/Routes/ToDoRoutes.js
- Server/Routes/UserRoutes.js
- Server/package-lock.json
- Server/package.json
- Server/security/sanitizeMiddleware.js
- package.json
Fix errors (missing dependencies, file extensions, and removing package.json from root)
Fixes #604
> Refactor imports to include file extensions and update dependencies for Argon2 and rate limiting

- Client/.env.example
- Client/package-lock.json
- Client/src/App.jsx
- Client/src/components/settings/Sidebar.jsx
- Client/src/components/settings/TimeLanguage.jsx
**I have removed the Language selector from Settings menu.**
> Remove Language Selector

- Client/package-lock.json
- Client/src/components/friendsSection/Avatar.jsx
- Client/src/components/friendsSection/FriendsRequests.jsx
- Client/src/components/friendsSection/SuggestedFriends.jsx
> Fix: Show the default profile picture for suggested friends who don’t already have one. #614

- Client/package-lock.json
- Client/src/components/friendsSection/Avatar.jsx
- Client/src/components/friendsSection/FriendsRequests.jsx
> Fix: The user profile gets squeezed if it has longer Bio. #509

- Client/src/components/home/goals/GoalsComponent.jsx
- Client/src/components/home/navBar/Slogan.jsx
The issue stated by @RishuKumarCodes that there is unnecessary log on console and should be removed .
Fixes #629 
Commneted out the console.log components in teh respective mentioned file :
Slogan.jsx
Goalscomponents.jsx
> remove unnecessary log from console

- .github/PULL_REQUEST_TEMPLATE.md
As per the suggestion on #631 by @RishuKumarCodes , updated the checklist to add more things 
Fixes #
> Updated the checklist in the PR template

- .github/workflows/issue-create-automate-message.yml
- .github/workflows/pr-validation.yml
Added the autocomment message on the issues by use of github actions bot by configuring the workflow file for the same purpose.
Fixes #627
> Add automated comment on newly opened issues

- Client/src/components/notes/NoteCard.jsx
- Client/src/components/notes/NoteEditor.jsx
- Client/src/components/notes/NoteHeader.jsx
- Client/src/components/notes/NotesList.jsx
- Client/src/components/notes/ToolbarButton.jsx
- Client/src/components/notes/note.css
- Client/src/pages/Notes.jsx
Refactored `Notes.jsx` into seperate components
Fixes #648
-[x] created seperate components for notes tab while keeping the same functionality
> Refactored Notes.jsx

- Client/src/components/notes/NoteCard.jsx
- Client/src/components/notes/NoteEditor.jsx
- Client/src/components/notes/NoteHeader.jsx
- Client/src/components/notes/NotesList.jsx
- Client/src/components/notes/ToolbarButton.jsx
- Client/src/components/notes/note.css
- Client/src/pages/Notes.jsx
> Revert "Revert "Refactored Notes.jsx""

- Client/src/components/settings/Account.jsx
Added navigation to the change your password section
Fixes #660
>  Change your Password section have a link for better navigation

- Client/src/components/ConfirmRemoveFriendModal.jsx
- Client/src/components/settings/Friends.jsx
Add confirm model when removing friend
Fixes #658
https://github.com/user-attachments/assets/a88a860f-2851-45d9-b29c-dc781a3d93db
> Add ConfirmRemoveFriendModal component and integrate with Friends list

- Server/.env.example
- Server/index.js
- Server/package.json
Disabled morgan on production, added env variables and updated script in package.json
Fixes #683
> use morgan only on development

- Client/src/api/NoteApi.js
- Client/src/components/notes/NoteCard.jsx
- Client/src/components/notes/NotesList.jsx
- Client/src/pages/Notes.jsx
- Client/src/queries/NoteQueries.js
- Server/Controller/NotesController.js
- Server/Model/NoteModel.js
> Created/Refactored notes backend 

- Client/src/Auth/SignUp.jsx
- Server/Controller/AuthController.js
Fix the token which was sent by signup and has no use
Fixes #708
> update signup process

- Server/Controller/AuthController.js
- Server/Routes/AuthRoutes.js
Add missing middleware and enhance deleteAccount by removes the deleted user from friends, requests, kudos, and collaborators, and deletes their owned notes, events, sessions.
Fixes #701
> enhance deleteAccount functionality and update AuthRoutes for middleware

- .github/workflows/issue-create-automate-message.yml
fix auto-comment script 
Fixes #734
> fix: update auto-comment script for issue creation

- Server/Controller/EventController.js
#784 
**Summary**
- This PR refactors EventController.js to improve maintainability and consistency without changing any functionality.
**Changes Made**
- Added handleError helper for centralized error handling.
- Added findUserEvent helper to ensure events belong to authenticated users.
- Replaced inline error responses with handleError.
- Improved logging with console.error for better debugging.
- Simplified deleteEvent by reusing findUserEvent.
- Kept all validation and business logic intact.
**How to Test**
- Run all event APIs (create, getAll, getByDate, getById, update, delete).
- Verify error responses are consistent.
- Ensure only authenticated user’s events are accessible.
- Try deleting/updating unauthorized events → should return 404.
> Refactor EventController.js for better maintainability

- Client/src/components/about/IdeaBehind.jsx
Updated the Idea behind eduhaven section with the draft you reviewed with the necessary changes you asked.
Fixes #805 
Before
After
> Updated idea behind section

- Server/Controller/EventController.js
- Server/Controller/UserController.js
#785 
**Description**
- This PR optimizes the UserController.js file to improve readability, validation, and maintainability while preserving all existing functionality.
**Changes Made**
-  Centralized input validation for updateProfile (forbidden fields, graduation year, bio length, and OtherDetails).
- Replaced inline validation checks with reusable and consistent logic.
- Ensured consistent error handling and improved error messages.
- Simplified Cloudinary upload logic with clear validation steps.
- Optimised relationship status logic in getUserDetails for clarity.
- Improved badge retrieval and awarding process with robust error handling.
- Enhanced logging to provide meaningful context while removing redundant logs.
- Cleaned up giveKudos logic to avoid duplicate kudos and ensure …
> Refactor UserController.js for Performance, Validation, and Maintainability

- Client/package-lock.json
- Client/package.json
- Client/src/components/chats/chatwindow.tsx
This PR addresses the issue #780 , it adds the emoji option in the chat window 
Fixes #780
> Feature : Add emoji option in the chat

- Client/src/components/session/OtherRooms.jsx
- Client/src/components/stats/Leaderboard.jsx
Sync leaderboard frontend logic with correct user. Basically this PR fixes differentiate frontend logic between logged in user and other read-only users.
Fixes #741 
https://github.com/user-attachments/assets/e61c313d-efc8-4ec8-aa82-f42c9b29cf0b
> Sync Leaderboard Frontend with Correct User

- Client/src/api/userApi.js
- Client/src/components/chats/userlist.tsx
- Client/src/pages/Chats.jsx
- Client/src/queries/userQueries.js
- Server/Controller/UserController.js
- Server/Routes/UserRoutes.js
Properly handled the search bar functionality as per the issue.
Fixes #830 
- Adeed `Client/src/api/userApi.js` added for fetching all users in frontend
- Updated `Client/src/components/chats/userlist.tsx`
- Updated `Client/src/pages/Chats.jsx`
- Added `Client/src/queries/userQueries.js` for fetching backend
- Updated `Server/Controller/UserController.js`
- Updated `Server/Routes/UserRoutes.js`
> Fix the issues in search functionality of chat

- Client/src/components/friendsPage/TabNavigation.jsx
- Client/src/components/settings/Sidebar.jsx
This PR refactors the **Friends page sidebar (`TabNavigation.jsx`)** to visually match the **Settings sidebar (`Sidebar.jsx`)**, ensuring consistent UI/UX across the app.  
Key improvements:
- Unified spacing, padding, alignment, and color scheme.
- Added `lucide-react` icons to each tab for clarity and aesthetics.
- Updated Settings sidebar to use the `<Button/>` component for tab navigation, aligning animations and accessibility with the Friends sidebar.
No visual changes were made to the Settings sidebar—only interactivity and code consistency were improved.
Fixes #842
Before:
After:
This update unifies sidebar appearance and behavior across the app, making the overall UX more cohesive and professional, while also improving maintainability by standardizing sidebar implementations.
> FIX: update the UI of sidebar in friends and settings page

- Server/Controller/StudySessionController.js
- Server/Controller/UserController.js
- Server/utils/streakUpdater.js
fixed the current streak reset issue.
Fixes #778
- fixed the cuurent streak issue since streaks are only updated when user study more than 10 minutes. If he study less than 10 min or not study at all the function will not run at all. Fixed that by applying the studytime condition while only changing streak and don't return immediately.
> Fix current and max streak of user.

- Server/Controller/AuthController.js
i have removed Bcrypt from the CodeBase and replaced it with Argon2
Fixes #756
> Bcrypt-removed

- Client/src/components/home/notes/NotesComponent.jsx
> Revert "feat: Global State fornotes data"

- Client/src/components/settings/Friends.jsx
> Update Friends.jsx #843

- Client/src/components/stats/ProfileCard/ProfileCard.jsx
Show username in the userProfile card. #810
issue number - 810
>  Show username in the userProfile card issue-810

- Client/src/components/stats/ProfileCard/FriendsPopup.jsx
- Server/Controller/FriendsController.js
This PR enhances the friend list popup by displaying the username under the user’s full name.
[FEATURE] show username in friend list popup #813
> Display username in friend list popup

- Client/src/components/home/navBar/Slogan.jsx
Update styling of text in navbar
Fixes #845
> fix slogan text issue

- Client/src/components/ui/Popup.jsx
fix the hard coded value of popup
Fixes #883
> fix popup width

- Client/src/Auth/Login.jsx
- Client/src/Auth/SignUp.jsx
Fixed the hover styling based on active theme on `Continue with Google` button.
Fixes #844 
https://github.com/user-attachments/assets/97bc6218-04ce-4f16-b5ca-88a15ef02040
> Fixed google oauth btn frontend

- Client/src/api/friendApi.js
- Client/src/components/friendsPage/MainContent.jsx
- Client/src/components/friendsPage/TabNavigation.jsx
- Client/src/components/friendsPage/UserCard.jsx
- Client/src/components/friendsPage/tabs/SuggestedFriends.jsx
- Client/src/pages/FriendsPage.jsx
- Client/src/queries/friendQueries.js
- Server/Controller/FriendsController.js
Fixes #884
https://github.com/user-attachments/assets/c682e510-1cc7-4136-a285-4ca73507e017
> add search functionality and infinite scroll

- Client/src/components/friendsPage/tabs/SuggestedFriends.jsx
> Revert "Remove Extra scrollable div"

- Client/src/components/home/notes/BottomControls.jsx
- Client/src/components/home/notes/NotesComponent.jsx
add color support
Fixes #776
https://github.com/user-attachments/assets/5166d6c1-3bab-484d-b1f0-e8858627c2c7
> add color support
